server:
  port: 10010
spring:
  application:
    name: gateway #服务名称
  cloud:
    nacos:
      server-addr: localhost:80 #nacos地址
    gateway:
      routes:
        - id: user-service #路由标示，必须唯一
          uri: lb://userservice #路由目标地址
          predicates: #路由断言，判断是否符合规则
            - Path=/user/** #判断是否以/user开头
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
      default-filters:
        - AddRequestHeader=Truth,lalala!
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
